version: "3"

services: 
  monolithic:
    container_name: nginx-monolithic-node
    restart: unless-stopped
    build: ./monolithic

  users:
    container_name: nginx-microservicesUser-node
    restart: unless-stopped
    build: ./microservices/user-service
  
  cars:
    container_name: nginx-microservicesCar-node
    restart: unless-stopped
    build: ./microservices/car-service
  
  books:
    container_name: nginx-microservicesBook-node
    restart: unless-stopped
    build: ./microservices/book-service

  nginx:
    image: nginx:latest
    ports: 
      - "8080:8080"
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - monolithic
      - users
      - books
      - cars